name: Comment on Failed Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  spec_doc_generator:
    name: Check Generator Templates
    runs-on: ubuntu-22.04
    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@cdf26dcd488490c9939e9d4d62cab169c9e4f20d
        with:
          crystal: "1.15.0"
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Run generator tests
        run: crystal spec ./document-generator/spec/*
  comment_on_failed_test:
    permissions: write-all
    name: Check Generator Templates
    runs-on: ubuntu-22.04
    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@cdf26dcd488490c9939e9d4d62cab169c9e4f20d
        with:
          crystal: "1.15.0"
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Run generator tests
        run: crystal document-generator/scripts/check_docs.cr
      - name: Comment on PR if test failed
        if: failure()
        uses: exercism/pr-commenter-action@v1.5.1
        with:
          github-token: ${{github.token}}
          config-file: ".github/pr-commenter.yml"
          