name: Comment on Failed Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  spec_doc_generator:
    name: Check Generator Templates
    runs-on: ubuntu-26.04
    container:
      image: crystallang/crystal:1.20.3
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Run generator tests
        run: crystal spec ./document-generator/spec/*
  comment_on_failed_test:
    permissions: write-all
    name: Check Generator Templates
    runs-on: ubuntu-26.04
    container:
      image: crystallang/crystal:1.20.3
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Run generator tests
        run: crystal document-generator/scripts/check_docs.cr
      - name: Comment on PR if test failed
        if: failure()
        uses: exercism/pr-commenter-action@v1.5.2
        with:
          github-token: ${{github.token}}
          config-file: ".github/pr-commenter.yml"
