name: Tests
on:
  pull_request:
  push:
    branches:
    - main
  schedule:
    # Weekly.
    - cron: "0 0 * * 0"

jobs:
  exercises:
    name: Check exercises
    runs-on: ubuntu-latest
    # idea from https://github.com/actions/starter-workflows/blob/master/ci/crystal.yml
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Run tests
        run: make test-exercises
        # TODO: fix generators
        #run: make test-generator
