name: Tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Weekly.
    - cron: '0 0 * * 0'

jobs:
  generator:
    name: Check Generator Templates
    runs-on: ubuntu-22.04
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Run generator tests
        run: ./bin/test_specs
  template:
    name: Check file formatting
    runs-on: ubuntu-22.04
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Run file formatting
        run: crystal ./bin/check-format.cr
  exercises_1-6:
    name: Check exercises crystal 1.6
    runs-on: ubuntu-22.04
    container:
      image: crystallang/crystal:1.6
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Install jq
        run: apt-get update && apt-get install -y jq
      - name: Run tests
        run: ./bin/test-exercises.sh
  exercises_1-7:
    name: Check exercises crystal 1.7
    runs-on: ubuntu-22.04
    container:
      image: crystallang/crystal:1.7
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Install jq
        run: apt-get update && apt-get install -y jq
      - name: Run tests
        run: ./bin/test-exercises.sh
