name: Tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Weekly.
    - cron: '0 0 * * 0'

jobs:
  test-generator:
    name: Test Generator
    runs-on: ubuntu-24.04
    container:
      image: crystallang/crystal:1.17
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Run generator tests
        run: crystal spec test-generator
  test-generator-templates:
    name: Check Generator Templates
    runs-on: ubuntu-24.04
    container:
      image: crystallang/crystal:1.17
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Check generator templates tests
        run: ./bin/test_specs
  template:
    name: Check file formatting
    runs-on: ubuntu-24.04
    container:
      image: crystallang/crystal:1.17
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Run file formatting
        run: crystal ./bin/check-format.cr
  exercises:
    name: Check exercises Crystal ${{ matrix.crystal }}
    runs-on: ubuntu-24.04
    strategy:
      # Allows running the job multiple times with different configurations
      matrix:
        crystal: ["1.11", "1.12", "1.13", "1.14", "1.15.1"]
    container:
      image: crystallang/crystal:${{ matrix.crystal }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Install jq
        run: apt-get update && apt-get install -y jq
      - name: Run tests
        run: ./bin/test-exercises.sh
  exercises-windows:
    name: Check exercises Crystal on Windows
    runs-on: windows-2022
    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@5503f15cfd350dfc402f9c2f0fa31bdf83fd7384
        with:
          crystal: "1.15.1"
      - name: 'Setup jq'
        run: choco install jq
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Run tests
        run: ./bin/test-exercises.ps1
